# Generated by Django 4.0.2 on 2022-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=15)),
                ('candle_date_time_utc', models.DateTimeField()),
                ('candle_date_time_kst', models.DateTimeField()),
                ('opening_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_price', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('candle_acc_trade_price', models.FloatField()),
                ('candle_acc_trade_volume', models.FloatField()),
                ('unit', models.IntegerField()),
            ],
            options={
                'unique_together': {('market', 'candle_date_time_kst')},
            },
        ),
    ]
