# Generated by Django 4.0.2 on 2022-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTickerModel',
            fields=[
                ('market', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('korean_name', models.CharField(max_length=15)),
                ('english_name', models.CharField(max_length=15)),
            ],
        ),
    ]
